name: eda
channels:
  - conda-forge
dependencies:
  - conda-forge::jupyterlab
  - conda-forge::seaborn
  - conda-forge::pandas
  - conda-forge::pandas-profiling
  - conda-forge::pyarrow
  - conda-forge::wandb
