name: nyc_airbnb_dev
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.8
  - conda-forge::ipython=7.21.0
  - conda-forge::mlflow
  - conda-forge::notebook
  - conda-forge::jupyterlab
  - conda-forge::cookiecutter
  - conda-forge::hydra-core
  - conda-forge::matplotlib
  - conda-forge::pandas
  - conda-forge::git
  - conda-forge::wandb
